import type { PortfolioData } from './types';

/* ────────────────────────── Default content ────────────────────────── */

export const DEFAULT_DATA: PortfolioData = {
  name: 'Arsh Srivastava',
  role: 'AI · Full-Stack · Software Developer',
  email: 'arxh.dev3@gmail.com',
  location: 'India · GMT+5:30',
  heroLines: ['Building Scalable', 'products for', 'real-world impact.'],
  heroSub:
    "I am a full-stack developer with a passion for building AI-native products. I work best on projects that require a blend of front-end polish, robust backend architecture, and smart AI integrations.",
  navLinks: [
    { label: 'About', href: '#about' },
    { label: 'Work', href: '#work' },
    { label: 'Capabilities', href: '#capabilities' },
    { label: 'Contact', href: '#contact' },
  ],
  disciplines: ['AI / ML', 'Full-Stack', '3D / WebGL', 'Systems'],
  marqueeWords: [
    'AI-Native Products',
    'Full-Stack Engineering',
    'Three.js & WebGL',
    'Real-Time Systems',
    'Design Systems',
    'Motion & Interaction',
  ],
  about: {
    paragraphs: [
      "I'm Arsh Srivastava, currently a final year B.Tech student. I'm a full-stack software developer who builds products where AI isn't a bolted-on feature, it's part of the architecture from day one. Most of my work sits at the intersection of a fast, well-engineered backend and an interface that feels considered rather than assembled.",
      "I am also a national level team sports player which proves I am not only a team player but also someone who takes casre of his health. I love to interact with people and learn as many new skills as possible."
    ],
    facts: [
      { label: 'Based in', value: 'India, working globally' },
      { label: 'Internship', value: 'React Native Developer - SyinQ' },
      { label: 'Open to', value: 'Freelance, collaborations & full-time roles' },
    ],
    currently: 'I am the product that needs to be sold on this website. Explore more to know me better.',
    initials: 'AS',
    photoSrc: '/Arsh Image.PNG',
    ringText: 'ARSH SRIV ✦ FULL-STACK DEV ✦ AI-NATIVE ✦ SOFTWARE DEV ✦ ',
  },
  capabilities: [
    { id: 'c1', number: '01', title: 'AI & ML Integration', description: 'LLM-powered features, agentic workflows, and RAG pipelines built into the product, not bolted on after.', tags: ['OpenAI', 'LangChain', 'Vector DBs'] },
    { id: 'c2', number: '02', title: 'Full-Stack Engineering', description: 'End-to-end product builds with typed APIs, real databases, and interfaces that hold up under real usage.', tags: ['Next.js', 'Node.js', 'PostgreSQL'] },
    { id: 'c3', number: '03', title: '3D & WebGL', description: 'Interactive Three.js scenes and product visualizations, optimized to actually run well on real devices.', tags: ['Three.js', 'R3F', 'elevenlabs'] },
    { id: 'c4', number: '04', title: 'Motion & Interaction', description: 'Purposeful micro-interactions and page transitions that reinforce what the interface is doing.', tags: ['anime.js', 'GSAP', 'Framer Motion'] },
    { id: 'c5', number: '05', title: 'System Design', description: 'Designs scalable systems that not only work for 100 users but also for 100 million users on cloud platform.', tags: ['Kafka', 'Docker', 'Kubernates'] },
    { id: 'c6', number: '06', title: 'Competitive Programming', description: 'I compete in various competitive programming platforms and have a 4+ Star on Codeforces, while also being finalist at many hackathons.', tags: ['Hackathons', 'Competetive Programming'] },
  ],
  work: [
    {
      id: 'w1',
      title: 'SkillCAD EV',
      year: '2026',
      description: 'Architected AWS cloud infrastructure streaming high-throughput telemetry into Kafka and MongoDB cluster.\nEngineered LangGraph multi-agent workflows and NetworkX graph models for predictive battery analytics.',
      tags: ['LangGraph', 'Gemini', 'Kafka', 'DynamoDB', 'AWS', 'FastAPI'],
      image: "Skill_CAD EV.png",
      link: 'https://lnkd.in/p/gdKcnxwb',
      gradient: 'linear-gradient(135deg, #16241b, #34d399 150%)',
    },
    {
      id: 'w2',
      title: 'SwiftTrans',
      year: '2025',
      description: 'Built distributed CockroachDB backend infrastructure scaling transactional throughput three times under load.\nIntegrated automated GenAI transaction validation pipelines using Vercel AI SDK and JWTs.',
      tags: ['Gen AI', 'Vercel AI SDK', 'CockroachDB', 'JavaScript', 'REST API'],
      image: "SwiftTrans.png",
      link: 'https://www.linkedin.com/posts/arshsrivastava72235a300_ai-blockchain-fintech-activity-7319687328979988480-6c9N?utm_source=share&utm_medium=member_desktop&rcm=ACoAAEzwQIoBgt53V93G9_GxPjAhHg71aKHfCtk',
      gradient: 'linear-gradient(135deg, #281f14, #fbbf24 150%)',
    },
    {
      id: 'w3',
      title: 'Git (git-scm) — Open Source Contribution',
      year: '2026',
      description: 'Contributed upstream C codebase patches improving CLI checkout advisory messaging for developers.\nEnhanced terminal user experience and error diagnostics within core Git source tree.',
      tags: ['C', 'Git Internals', 'Open Source', 'CLI Tooling'],
      image: "git.png",
      link: 'https://github.com/git/git/pull/2233',
      gradient: 'linear-gradient(135deg, #2b1814, #f97316 150%)',
    },
    {
      id: 'w4',
      title: 'KalaKatha',
      year: '2025',
      description: 'Developed full-stack Flutter mobile application featuring OAuth security and geospatial discovery APIs.\nIntegrated digital payment gateways and GenAI toolsets empowering traditional artisan commerce networks.',
      tags: ['Flutter', 'Firebase', 'Vercel AI SDK', 'Google Maps'],
      image: "Kalakatha.png",
      link: 'https://github.com/Arsh123344423/KalaKatha',
      gradient: 'linear-gradient(135deg, #2a1622, #f43f5e 150%)',
    },
    {
      id: 'w5',
      title: 'VectorShift',
      year: '2026',
      description: 'Designed interactive ReactFlow canvas for dynamic AI workflow orchestration and DAG execution.\nImplemented modular Python and Node.js microservices executing scalable LLM agent pipelines reliably.',
      tags: ['ReactFlow', 'LLM Agents', 'React', 'Node.js', 'Python'],
      image: "VectorShift.png",
      link: 'https://www.linkedin.com/posts/arshsrivastava72235a300_a-small-peak-of-what-i-am-planning-to-create-activity-7472325967487840257-Vc4r?utm_source=share&utm_medium=member_desktop&rcm=ACoAAEzwQIoBgt53V93G9_GxPjAhHg71aKHfCtk',
      gradient: 'linear-gradient(135deg, #1c182c, #818cf8 150%)',
    },
    {
      id: 'w6',
      title: 'PLQ — PII Redaction Pipeline',
      year: '2026',
      description: 'Engineered enterprise data anonymization pipeline combining spaCy Presidio and Scikit-learn NER models.\nDelivered high-precision structured entity extraction with consistent replacement mapping for enterprise privacy.',
      tags: ['NER', 'spaCy', 'Presidio', 'Scikit-learn', 'Python', 'Data Security'],
      image: "plq.png",
      link: 'https://github.com/Arsh123344423/PlQ',
      gradient: 'linear-gradient(135deg, #142232, #38bdf8 150%)',
    },
  ],
  stats: [
    { id: 's1', value: '2', suffix: '+', label: 'Years Building', note: 'From first line of code to shipped, maintained products.' },
    { id: 's2', value: '6', suffix: '+', label: 'Products Shipped', note: 'Across web, mobile, and embedded 3D contexts.' },
    { id: 's3', value: '3', label: 'AI-Native Products', note: 'AI woven into the architecture, never bolted on after.' },
    { id: 's4', value: '100', suffix: '%', label: 'Design-to-Code Handoff', note: 'Every pixel and token accounted for in the build.' },
  ],
  socials: [
    { label: 'Twitter', href: 'https://x.com/ArshSri01642844' },
    { label: 'GitHub', href: 'https://github.com/Arsh123344423' },
    { label: 'LinkedIn', href: 'https://www.linkedin.com/in/arshsrivastava72235a300/' },
    { label: 'CodersRank', href: 'https://profile.codersrank.io/user/arsh123344423/' },
  ],
};
